### ISSUE TITLE
Condense stylesheet size by using the average width and height of the sprites

### ISSUE THREAD

**Issue by ghost** [draeton/stitches#37]
Stitches successfully generated this sprite sheet: 
![](https://cloud.githubusercontent.com/assets/4117838/7102300/3037c652-e07c-11e4-9b3c-ff5c70eb521b.png)

Almost all flags are 16x11 in size, but two of them are 11x11, so the stylesheet looks like this:

``` css
.flags {
    background-image: url(spritesheet.png);
    background-repeat: no-repeat;
    display: block;
}

.flags-ad {
    width: 16px;
    height: 11px;
    background-position: 0 0;
}

/* ... */

.flags-ch {
    width: 11px;
    height: 11px;
    background-position: -192px 0;
}
```

The approach is simple: .flags would be 16x11 in size, and the width and height properties would be omitted in every sprite unless its size differs from the average, something like this:

``` css
.flags {
    width: 16px;
    height: 11px;
    background-image: url(spritesheet.png);
    background-repeat: no-repeat;
    display: block;
}

.flags-ad {
    background-position: 0 0;
}

/* ... */

.flags-ch {
    width: 11px;
    background-position: -192px 0;
}
```

Apart from that, Stitches is a great and useful tool, nice job!
